/**
 * brain.js — Greg's Sales Intelligence Layer
 *
 * Connects Greg (Telegram bot) to Supabase + Claude API to:
 *   1. Auto-classify messages from @sales_bolismedia chats via userClient
 *   2. Create/update deals automatically from conversation context
 *   3. Extract lessons from deal conversations nightly
 *   4. Answer pipeline questions with AI-powered closing advice
 *   5. Send daily morning recaps to Greg+ Sales Team group
 *
 * Env vars required:
 *   ANTHROPIC_API_KEY          — Claude API key
 *   SUPABASE_URL               — Bolis Command Center project URL
 *   SUPABASE_SERVICE_ROLE_KEY  — Service role key (bypasses RLS)
 *   TELEGRAM_API_ID            — from my.telegram.org
 *   TELEGRAM_API_HASH          — from my.telegram.org
 *   TELEGRAM_SESSION           — generated by setup-session.js
 *   GREG_SALES_CHAT            — Greg+ Sales Team group username or ID
 */

require("dotenv").config();
const Anthropic        = require("@anthropic-ai/sdk");
const { createClient } = require("@supabase/supabase-js");
const userClient       = require("./userClient");

// ── Clients ───────────────────────────────────────────────────────────────────

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

// Bot instance — set by wizard.js so recaps are sent from Greg (bot), not @sales_bolismedia
let _bot = null;
const SALES_CHAT = process.env.GREG_SALES_CHAT || "";

function setBotInstance(bot) { _bot = bot; }

async function sendRecapViaBot(text) {
  if (_bot && SALES_CHAT) {
    try {
      await _bot.telegram.sendMessage(SALES_CHAT, text, { parse_mode: "Markdown" });
      return true;
    } catch (e) {
      console.warn("[brain] Bot recap failed, falling back to userClient:", e.message);
    }
  }
  // Fallback to userClient if bot not available
  await userClient.sendRecap(text);
  return true;
}

// ── Auto-capture listener startup ─────────────────────────────────────────────
// Call once at startup — Greg listens to ALL chats @sales_bolismedia is in.

async function startAutoCapture() {
  try {
    await userClient.onNewMessage(async ({ chatId, chatName, msgId, text, sender }) => {
      if (!text?.trim()) return;
      await captureMessage(chatId, msgId, sender, text, chatName);
    });
    console.log("[brain] 🎯 Auto-capture active — monitoring @sales_bolismedia chats");
  } catch (e) {
    console.warn("[brain] Auto-capture unavailable (check TELEGRAM_* env vars):", e.message);
  }
}

// ── Message classification ────────────────────────────────────────────────────
// Ask Claude whether a message is sales-relevant and what action to take.

const CLASSIFY_SYSTEM = `You are Greg, a sales intelligence assistant for Bolis Media — a social media marketing agency.
Your job is to classify Telegram messages from the sales team and determine if they relate to sales pipeline activity.

Return ONLY valid JSON matching this schema:
{
  "relevant": boolean,           // is this sales-relevant?
  "action": "new_deal" | "update_deal" | "lesson" | "ignore",
  "client_name": string | null,  // extracted client/prospect name if present
  "status": "lead" | "active" | "negotiating" | "closed" | "lost" | null,
  "value": number | null,        // deal value in dollars if mentioned
  "owner_handle": string | null, // @handle of person handling this deal
  "summary": string | null,      // 1-sentence summary of what happened
  "lesson": string | null        // if action==="lesson", the insight to save
}

Be conservative — only mark relevant=true if the message clearly relates to a sales deal, prospect, or negotiation.
Ignore operational messages about ad posting, scheduling, content, or internal logistics.
Respond with raw JSON only, no markdown formatting or code fences.`;

async function classifyMessage(senderHandle, text) {
  try {
    const msg = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 256,
      system: CLASSIFY_SYSTEM,
      messages: [{ role: "user", content: `Sender: @${senderHandle}\nMessage: ${text}` }],
    });
    let raw = msg.content[0]?.text?.trim() || "{}";
    raw = raw.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/g, '').trim();
    return JSON.parse(raw);
  } catch (e) {
    console.error("[brain] classifyMessage error:", e.message);
    return { relevant: false, action: "ignore" };
  }
}

// ── Auto-capture pipeline ─────────────────────────────────────────────────────

async function captureMessage(chatId, messageId, senderHandle, text, chatName = null) {
  // 1. Store raw message (deduped by chat_id + message_id)
  const { error: insertErr } = await supabase
    .from("deal_messages")
    .upsert({
      chat_id:        chatId,
      message_id:     messageId,
      sender_handle:  senderHandle,
      message_text:   text,
      classified:     false,
    }, { onConflict: "chat_id,message_id" });

  if (insertErr) {
    console.error("[brain] captureMessage insert error:", insertErr.message);
    return;
  }

  // 2. Classify with Claude
  const result = await classifyMessage(senderHandle, text);
  if (!result.relevant) {
    // Mark classified so we don't re-process
    await supabase
      .from("deal_messages")
      .update({ classified: true })
      .eq("chat_id", chatId)
      .eq("message_id", messageId);
    return;
  }

  console.log(`[brain] 🎯 Sales signal from @${senderHandle}: ${result.action} — ${result.summary}`);

  // 3. Act on classification
  if (result.action === "new_deal" && result.client_name) {
    // Check if deal already exists for this client
    const { data: existing } = await supabase
      .from("deals")
      .select("id")
      .ilike("client_name", result.client_name)
      .not("status", "in", '("closed","lost")')
      .maybeSingle();

    let dealId;
    if (existing) {
      dealId = existing.id;
      // Update if we have new info
      const updates = {};
      if (result.status)       updates.status       = result.status;
      if (result.value)        updates.value        = result.value;
      if (result.owner_handle) updates.owner_handle = result.owner_handle.replace(/^@/, "");
      if (Object.keys(updates).length) {
        await supabase.from("deals").update(updates).eq("id", dealId);
      }
    } else {
      const { data: newDeal } = await supabase
        .from("deals")
        .insert({
          client_name:    result.client_name,
          status:         result.status || "lead",
          value:          result.value  || null,
          owner_handle:   result.owner_handle?.replace(/^@/, "") || senderHandle,
          source_chat_id: chatId,
          notes:          result.summary || null,
        })
        .select("id")
        .single();
      dealId = newDeal?.id;

      // Log activity
      if (dealId) {
        await supabase.from("deal_activities").insert({
          deal_id:  dealId,
          activity: `Deal created: ${result.summary || result.client_name}`,
          actor:    senderHandle,
        });
      }
    }

    // Link message to deal
    if (dealId) {
      await supabase
        .from("deal_messages")
        .update({ deal_id: dealId, classified: true })
        .eq("chat_id", chatId)
        .eq("message_id", messageId);
    }
  }

  if (result.action === "update_deal" && result.client_name) {
    const { data: deal } = await supabase
      .from("deals")
      .select("id, status")
      .ilike("client_name", result.client_name)
      .not("status", "in", '("closed","lost")')
      .maybeSingle();

    if (deal) {
      const updates = {};
      if (result.status && result.status !== deal.status) updates.status = result.status;
      if (result.value)        updates.value        = result.value;
      if (result.owner_handle) updates.owner_handle = result.owner_handle.replace(/^@/, "");
      if (Object.keys(updates).length) {
        await supabase.from("deals").update(updates).eq("id", deal.id);
        await supabase.from("deal_activities").insert({
          deal_id:  deal.id,
          activity: result.summary || `Updated: ${Object.keys(updates).join(", ")}`,
          actor:    senderHandle,
        });
      }
      await supabase
        .from("deal_messages")
        .update({ deal_id: deal.id, classified: true })
        .eq("chat_id", chatId)
        .eq("message_id", messageId);
    }
  }

  if (result.action === "lesson" && result.lesson) {
    await supabase.from("sales_lessons").insert({
      lesson:  result.lesson,
      context: result.summary || null,
      source_message_ids: JSON.stringify([{ chat_id: chatId, message_id: messageId }]),
    });
    await supabase
      .from("deal_messages")
      .update({ classified: true })
      .eq("chat_id", chatId)
      .eq("message_id", messageId);
  }
}

// ── Pipeline summary ──────────────────────────────────────────────────────────

const PIPELINE_SYSTEM = `You are Greg, a sharp sales assistant for Bolis Media — a social media marketing agency.
Given a list of open deals and recent sales lessons, provide:
1. A concise pipeline summary (who's close, who needs attention)
2. For each active deal: one concrete next action to move it forward
3. Any patterns you see across deals

Be direct, specific, and actionable. Keep it under 400 words.

FORMATTING RULES (strict — this is for Telegram, not a web page):
- NO markdown: no **, ##, ---, or \`backticks\`
- Use emoji bullets: 🔥 🎯 📌 ⚠️ ✅ etc.
- Use plain line breaks to separate sections
- Use ALL CAPS or emoji for emphasis instead of bold/italic
- Keep it scannable — short lines, not dense paragraphs`;

async function getPipelineSummary() {
  // Pull open deals
  const { data: deals } = await supabase
    .from("deals")
    .select("client_name, status, value, owner_handle, notes, created_at, updated_at")
    .not("status", "in", '("closed","lost")')
    .order("updated_at", { ascending: false });

  if (!deals?.length) return "📭 No open deals in the pipeline right now.";

  // Pull recent lessons (last 10)
  const { data: lessons } = await supabase
    .from("sales_lessons")
    .select("lesson, context")
    .order("created_at", { ascending: false })
    .limit(10);

  const dealsText = deals.map((d) =>
    `- ${d.client_name} | ${d.status}${d.value ? ` | $${d.value}` : ""}${d.owner_handle ? ` | @${d.owner_handle}` : ""}${d.notes ? ` | ${d.notes}` : ""}`
  ).join("\n");

  const lessonsText = lessons?.length
    ? lessons.map((l) => `- ${l.lesson}`).join("\n")
    : "No lessons recorded yet.";

  try {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 600,
      system: PIPELINE_SYSTEM,
      messages: [{
        role: "user",
        content: `OPEN DEALS:\n${dealsText}\n\nRECENT SALES LESSONS:\n${lessonsText}`,
      }],
    });
    return msg.content[0]?.text?.trim() || "Could not generate summary.";
  } catch (e) {
    console.error("[brain] getPipelineSummary error:", e.message);
    return "⚠️ Could not generate pipeline summary right now.";
  }
}

// ── Deal-specific advice ──────────────────────────────────────────────────────

async function getDealAdvice(clientName) {
  // Find deal
  const { data: deal } = await supabase
    .from("deals")
    .select("*")
    .ilike("client_name", `%${clientName}%`)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!deal) return `❌ No deal found matching "${clientName}".`;

  // Pull messages for this deal
  const { data: messages } = await supabase
    .from("deal_messages")
    .select("sender_handle, message_text, captured_at")
    .eq("deal_id", deal.id)
    .order("captured_at", { ascending: true })
    .limit(30);

  // Pull lessons
  const { data: lessons } = await supabase
    .from("sales_lessons")
    .select("lesson")
    .order("created_at", { ascending: false })
    .limit(5);

  const convoText = messages?.length
    ? messages.map((m) => `@${m.sender_handle}: ${m.message_text}`).join("\n")
    : "No conversation history recorded yet.";

  const lessonsText = lessons?.length
    ? lessons.map((l) => `- ${l.lesson}`).join("\n")
    : "";

  try {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 500,
      system: `You are Greg, a sales advisor for Bolis Media. Analyze this deal and give specific, actionable closing advice.
FORMATTING: This is for Telegram. NO markdown (no **, ##, ---, backticks). Use emoji bullets and ALL CAPS for emphasis. Short lines, not paragraphs.`,
      messages: [{
        role: "user",
        content: `DEAL: ${deal.client_name} | ${deal.status}${deal.value ? ` | $${deal.value}` : ""}
Notes: ${deal.notes || "none"}

CONVERSATION HISTORY:
${convoText}

${lessonsText ? `RELEVANT LESSONS:\n${lessonsText}` : ""}

What should we do next to close this deal?`,
      }],
    });
    return `💼 *${deal.client_name}* (${deal.status})\n\n${msg.content[0]?.text?.trim()}`;
  } catch (e) {
    console.error("[brain] getDealAdvice error:", e.message);
    return "⚠️ Could not generate deal advice right now.";
  }
}

// ── Nightly lesson extraction ─────────────────────────────────────────────────
// Runs once a day — scans closed deals from last 7 days and extracts lessons.

async function extractNightlyLessons() {
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  const { data: recentDeals } = await supabase
    .from("deals")
    .select("id, client_name, status, notes")
    .in("status", ["closed", "lost"])
    .gte("updated_at", sevenDaysAgo);

  if (!recentDeals?.length) return 0;

  let extracted = 0;
  for (const deal of recentDeals) {
    const { data: messages } = await supabase
      .from("deal_messages")
      .select("sender_handle, message_text")
      .eq("deal_id", deal.id)
      .order("captured_at", { ascending: true })
      .limit(50);

    if (!messages?.length) continue;

    const convoText = messages.map((m) => `@${m.sender_handle}: ${m.message_text}`).join("\n");

    try {
      const msg = await anthropic.messages.create({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 400,
        system: `You are a sales coach analyzing completed deals for Bolis Media. Extract 1-3 concrete, reusable lessons from this conversation. Return ONLY a JSON array of strings. Example: ["Lesson one.", "Lesson two."]`,
        messages: [{
          role: "user",
          content: `Deal: ${deal.client_name} — ${deal.status}\n\n${convoText}`,
        }],
      });

      const raw = msg.content[0]?.text?.trim() || "[]";
      const lessons = JSON.parse(raw);
      for (const lesson of lessons) {
        await supabase.from("sales_lessons").insert({
          lesson,
          context:  `Extracted from ${deal.status} deal: ${deal.client_name}`,
          deal_id:  deal.id,
        });
        extracted++;
      }
    } catch (e) {
      console.error(`[brain] extractNightlyLessons error for ${deal.client_name}:`, e.message);
    }
  }

  console.log(`[brain] 🎓 Extracted ${extracted} lessons from ${recentDeals.length} recent deals.`);
  return extracted;
}

// ── Morning recap ─────────────────────────────────────────────────────────────
// Pulls open deals + recent lessons, generates a morning brief via Claude,
// and sends it to the Greg+ Sales Team group via @sales_bolismedia.

const RECAP_SYSTEM = `You are Greg, a sharp sales assistant for Bolis Media — a social media marketing agency.
Every morning you send the team a focused daily sales recap. Be direct, specific, and motivating.
Keep it under 500 words. Make every line actionable.

FORMATTING (strict — this is for Telegram, not a web page):
- NO markdown: no **, ##, ---, or backticks
- Use emoji bullets for sections and items: 🔥 🎯 📌 ⚠️ ✅ etc.
- Use ALL CAPS for emphasis instead of bold/italic
- Plain line breaks between sections — no horizontal rules
- Keep lines short and scannable`;

async function sendMorningRecap() {
  // Pull open deals
  const { data: deals } = await supabase
    .from("deals")
    .select("client_name, status, value, owner_handle, notes, updated_at")
    .not("status", "in", '("closed","lost")')
    .order("updated_at", { ascending: false });

  // Pull last 5 lessons
  const { data: lessons } = await supabase
    .from("sales_lessons")
    .select("lesson")
    .order("created_at", { ascending: false })
    .limit(5);

  // Pull deals that haven't been updated in 48h (need follow-up)
  const twoDaysAgo = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();
  const stale = (deals || []).filter((d) => d.updated_at < twoDaysAgo);

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric",
    timeZone: "America/Phoenix",
  });

  const dealsText = deals?.length
    ? deals.map((d) =>
        `- ${d.client_name} [${d.status}]${d.value ? ` $${d.value}` : ""}${d.owner_handle ? ` — @${d.owner_handle}` : ""}${d.notes ? `: ${d.notes}` : ""}`
      ).join("\n")
    : "No open deals.";

  const staleText = stale.length
    ? stale.map((d) => `- ${d.client_name} (${d.status}) — no update in 48h+`).join("\n")
    : "None";

  const lessonsText = lessons?.length
    ? lessons.map((l) => `- ${l.lesson}`).join("\n")
    : "None yet — keep logging wins and losses!";

  try {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 700,
      system: RECAP_SYSTEM,
      messages: [{
        role: "user",
        content: `Date: ${today}

OPEN PIPELINE (${deals?.length || 0} deals):
${dealsText}

NEEDS FOLLOW-UP (stale 48h+):
${staleText}

RECENT LESSONS:
${lessonsText}

Write the morning recap.`,
      }],
    });

    const recap = msg.content[0]?.text?.trim();
    if (recap) {
      await sendRecapViaBot(`🌅 GOOD MORNING — Daily Sales Recap\n${today}\n\n${recap}`);
      console.log("[brain] 📬 Morning recap sent");
    }
  } catch (e) {
    console.error("[brain] sendMorningRecap error:", e.message);
  }
}

// -- Nightly revenue recap ------------------------------------------------
// End-of-day summary: revenue closed today, pipeline movement, wins/losses,
// and a motivational wrap-up. Sent to Greg+ Sales Team group.

const NIGHTLY_RECAP_SYSTEM = `You are Greg, a sharp sales assistant for Bolis Media — a social media marketing agency.
Every night you send the team an end-of-day revenue recap. Cover:
1. Revenue closed TODAY (new deals closed, total value)
2. Pipeline movement (deals that advanced, went cold, or were lost)
3. Top wins and highlights of the day
4. Anything that needs attention tomorrow morning
5. A short motivational close — keep the energy up

Be direct, specific, and celebratory when there are wins.
Keep it under 500 words.

FORMATTING (strict — this is for Telegram, not a web page):
- NO markdown: no **, ##, ---, or backticks
- Use emoji bullets for sections and items: 💰 🔥 🎯 📌 ⚠️ ✅ 📈 🏆 etc.
- Use ALL CAPS for emphasis instead of bold/italic
- Plain line breaks between sections — no horizontal rules
- Keep lines short and scannable`;

async function sendNightlyRecap() {
  const now = new Date();
  const todayStart = new Date(now);
  todayStart.setHours(0, 0, 0, 0);
  const todayISO = todayStart.toISOString();

  const tonight = now.toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric",
    timeZone: "America/Phoenix",
  });

  // Deals closed/lost today
  const { data: closedToday } = await supabase
    .from("deals")
    .select("client_name, status, value, owner_handle")
    .in("status", ["closed", "lost"])
    .gte("updated_at", todayISO);

  // All open deals (pipeline snapshot)
  const { data: openDeals } = await supabase
    .from("deals")
    .select("client_name, status, value, owner_handle, notes, updated_at")
    .not("status", "in", '("closed","lost")')
    .order("updated_at", { ascending: false });

  // Today's deal activities
  const { data: activities } = await supabase
    .from("deal_activities")
    .select("deal_id, activity, actor, created_at")
    .gte("created_at", todayISO)
    .order("created_at", { ascending: false })
    .limit(20);

  // Recent lessons
  const { data: lessons } = await supabase
    .from("sales_lessons")
    .select("lesson")
    .order("created_at", { ascending: false })
    .limit(5);

  const closedText = closedToday?.length
    ? closedToday.map((d) =>
        `- ${d.client_name} [${d.status.toUpperCase()}]${d.value ? ` $${d.value}` : ""}${d.owner_handle ? ` — @${d.owner_handle}` : ""}`
      ).join("\n")
    : "No deals closed or lost today.";

  const totalClosed = (closedToday || [])
    .filter((d) => d.status === "closed")
    .reduce((sum, d) => sum + (d.value || 0), 0);

  const openText = openDeals?.length
    ? openDeals.map((d) =>
        `- ${d.client_name} [${d.status}]${d.value ? ` $${d.value}` : ""}${d.owner_handle ? ` — @${d.owner_handle}` : ""}`
      ).join("\n")
    : "No open deals.";

  const activityText = activities?.length
    ? activities.map((a) => `- ${a.activity} (by @${a.actor})`).join("\n")
    : "No deal activity logged today.";

  const lessonsText = lessons?.length
    ? lessons.map((l) => `- ${l.lesson}`).join("\n")
    : "None yet.";

  const totalPipelineValue = (openDeals || []).reduce((sum, d) => sum + (d.value || 0), 0);

  try {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 700,
      system: NIGHTLY_RECAP_SYSTEM,
      messages: [{
        role: "user",
        content: `Date: ${tonight}

CLOSED/LOST TODAY:
${closedText}
Total revenue closed today: $${totalClosed}

OPEN PIPELINE (${openDeals?.length || 0} deals, $${totalPipelineValue} total value):
${openText}

TODAY'S ACTIVITY:
${activityText}

RECENT LESSONS:
${lessonsText}

Write the nightly revenue recap.`,
      }],
    });

    const recap = msg.content[0]?.text?.trim();
    if (recap) {
      await sendRecapViaBot(`🌙 NIGHTLY REVENUE RECAP\n${tonight}\n\n${recap}`);
      console.log("[brain] 📬 Nightly recap sent");
    }
  } catch (e) {
    console.error("[brain] sendNightlyRecap error:", e.message);
  }
}

// -- Stake bet slip cover generation (via Digi) ---------------------------
// Analyzes a bet slip screenshot with Claude Vision, extracts headline and
// player search query, then calls Digi's API to render the cover image.

const DIGI_API_URL = process.env.DIGI_API_URL || "http://localhost:3000";
const DIGI_API_SECRET = process.env.DIGI_API_SECRET || "";

const BETSLIP_ANALYSIS_SYSTEM = `You are Greg, a sports media assistant for Bolis Media.
You are analyzing a screenshot of a betting slip to create a cover image and ad caption for social media.

From the bet slip, extract:
1. The teams/players involved
2. The sport (NBA, NFL, UFC, soccer, etc.)
3. A short, punchy headline (6-12 words) — make it sound like sports media, not a bet description. IMPORTANT: When the headline is split into 3 lines, every line must have at least 3 words. Avoid short 2-word phrases that would create oversized text.
4. Exactly 3 image options — ALL should show the top stars from each team TOGETHER:
   - Identify the biggest star from team 1 and the biggest star from team 2
   - Keep queries SHORT and simple — just the two player names + team names. Less is more for image search.
   - DO NOT add generic filler words like "matchup", "on court", "face to face", "guarding", "action shot"
   - DO NOT add the year — image search engines handle recency on their own
   - Vary queries slightly: use team abbreviations vs full names, swap player order
   - Example: Lakers vs Rockets → "LeBron James Jalen Green Lakers Rockets", "Jalen Green LeBron James NBA", "LeBron Jalen Green Houston LA"
   - Example: Knicks vs Hornets → "Jalen Brunson LaMelo Ball Knicks Hornets", "LaMelo Ball Jalen Brunson NBA", "Brunson LaMelo New York Charlotte"
5. An Instagram ad caption — short, engaging, sports-media style with relevant emojis and hashtags

The headline should be written in the style of sports media covers — dramatic, attention-grabbing.
Examples of good headlines:
- "LOS ANGELES HEADS TO HOUSTON AFTER A HUGE WIN AGAINST DENVER AT HOME"
- "CURRY DROPS 40 IN WARRIORS COMEBACK"
- "MAHOMES VS ALLEN THE REMATCH"

The caption should be 1-3 lines max, hype the matchup or bet, include 3-5 relevant hashtags.
Example caption: "The Spurs are LOCKED IN tonight 🔒🏀 Who's riding with us?\\n\\n#NBA #Spurs #SanAntonio #SportsBetting #Stake"

Return ONLY valid JSON:
{
  "teams": ["team1", "team2"],
  "sport": "NBA",
  "headline": "THE HEADLINE TEXT",
  "imageOptions": [
    { "label": "LeBron vs Jalen", "query": "LeBron James Jalen Green Lakers Rockets" },
    { "label": "LeBron & Jalen", "query": "Jalen Green LeBron James NBA basketball" },
    { "label": "Lakers Rockets", "query": "LeBron Jalen Green Houston Los Angeles" }
  ],
  "accentColor": "#hex color that matches the favored team",
  "caption": "The Instagram ad caption with emojis and hashtags"
}

Respond with raw JSON only, no markdown or code fences.`;

/**
 * Analyze a bet slip screenshot using Claude Vision.
 * Returns extracted info for cover generation.
 */
async function analyzeBetSlip(imageBase64, mimeType = "image/png") {
  try {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 400,
      system: BETSLIP_ANALYSIS_SYSTEM,
      messages: [{
        role: "user",
        content: [
          {
            type: "image",
            source: { type: "base64", media_type: mimeType, data: imageBase64 },
          },
          {
            type: "text",
            text: "Analyze this bet slip and generate the cover image data.",
          },
        ],
      }],
    });

    let raw = msg.content[0]?.text?.trim() || "{}";
    raw = raw.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```\s*$/g, "").trim();
    return JSON.parse(raw);
  } catch (e) {
    console.error("[brain] analyzeBetSlip error:", e.message);
    return null;
  }
}

/**
 * Generate a Stake bet slip cover by calling Digi's API.
 *
 * @param {string} betSlipBase64 - Base64-encoded bet slip screenshot
 * @param {string} [betSlipMime] - MIME type (default: image/png)
 * @param {object} [overrides] - Optional overrides for headline, accentColor, etc.
 * @returns {Promise<{success: boolean, imageBase64?: string, analysis?: object, error?: string}>}
 */
async function generateBetSlipCover(betSlipBase64, betSlipMime = "image/png", overrides = {}) {
  // 1. Analyze the bet slip with Claude Vision
  console.log("[brain] Analyzing bet slip with Claude Vision...");
  const analysis = await analyzeBetSlip(betSlipBase64, betSlipMime);
  if (!analysis || !analysis.headline) {
    return { success: false, error: "Could not analyze bet slip" };
  }

  console.log(`[brain] Bet slip analysis: ${analysis.headline} (${analysis.sport})`);
  console.log(`[brain] Image search query: ${analysis.imageSearchQuery}`);

  // 2. Call Digi's API to render the cover
  const requestBody = {
    headline: overrides.headline || analysis.headline,
    betSlipBase64,
    betSlipMime,
    bgImageSearch: overrides.bgImageSearch || analysis.imageSearchQuery,
    accentColor: overrides.accentColor || analysis.accentColor || "#FF3B30",
    brandText: overrides.brandText || "ODDS",
    returnFormat: "base64",
  };

  try {
    const headers = { "Content-Type": "application/json" };
    if (DIGI_API_SECRET) {
      headers["Authorization"] = `Bearer ${DIGI_API_SECRET}`;
    }

    console.log(`[brain] Calling Digi API at ${DIGI_API_URL}/api/stake/cover`);
    const res = await fetch(`${DIGI_API_URL}/api/stake/cover`, {
      method: "POST",
      headers,
      body: JSON.stringify(requestBody),
    });

    if (!res.ok) {
      const errText = await res.text();
      return { success: false, error: `Digi API error: ${res.status} — ${errText}`, analysis };
    }

    const data = await res.json();
    if (data.success && data.image) {
      console.log(`[brain] Cover generated (${Math.round(data.size / 1024)}KB)`);
      return { success: true, imageBase64: data.image, analysis };
    }

    return { success: false, error: data.error || "Unknown Digi error", analysis };
  } catch (e) {
    console.error("[brain] generateBetSlipCover Digi call error:", e.message);
    return { success: false, error: `Could not reach Digi: ${e.message}`, analysis };
  }
}

/**
 * Search for images via Digi API — returns thumbnails for each query.
 * @param {Array<{label: string, query: string}>} queries
 * @returns {Promise<Array<{label, query, base64, fullBase64}>>}
 */
async function searchBetSlipImages(queries) {
  try {
    const headers = { "Content-Type": "application/json" };
    if (DIGI_API_SECRET) headers["Authorization"] = `Bearer ${DIGI_API_SECRET}`;

    const res = await fetch(`${DIGI_API_URL}/api/stake/search-images`, {
      method: "POST",
      headers,
      body: JSON.stringify({ queries }),
    });

    if (!res.ok) {
      console.error("[brain] searchBetSlipImages failed:", res.status);
      return [];
    }

    const data = await res.json();
    return data.results || [];
  } catch (e) {
    console.error("[brain] searchBetSlipImages error:", e.message);
    return [];
  }
}

/**
 * Render a cover with a specific pre-fetched image (base64).
 * Called after user picks from image previews.
 */
async function renderCoverWithImage(betSlipBase64, betSlipMime, analysis, bgImageBase64) {
  console.log(`[brain] renderCoverWithImage: headline="${analysis.headline}", bgImage=${bgImageBase64 ? `${Math.round(bgImageBase64.length/1024)}KB` : 'null'}, betSlip=${betSlipBase64 ? `${Math.round(betSlipBase64.length/1024)}KB` : 'null'}`);
  const requestBody = {
    headline: analysis.headline,
    betSlipBase64,
    betSlipMime,
    bgImageBase64,
    accentColor: analysis.accentColor || "#FF3B30",
    brandText: "ODDS",
    returnFormat: "base64",
  };

  try {
    const headers = { "Content-Type": "application/json" };
    if (DIGI_API_SECRET) headers["Authorization"] = `Bearer ${DIGI_API_SECRET}`;

    console.log(`[brain] Sending cover request to Digi (body ~${Math.round(JSON.stringify(requestBody).length/1024)}KB)...`);
    const res = await fetch(`${DIGI_API_URL}/api/stake/cover`, {
      method: "POST",
      headers,
      body: JSON.stringify(requestBody),
    });

    if (!res.ok) {
      const errText = await res.text();
      return { success: false, error: `Digi API error: ${res.status} — ${errText}` };
    }

    const data = await res.json();
    if (data.success && data.image) return { success: true, imageBase64: data.image };
    return { success: false, error: data.error || "Unknown Digi error" };
  } catch (e) {
    return { success: false, error: `Could not reach Digi: ${e.message}` };
  }
}

/**
 * Render a cover with a specific image search query.
 * Called after user picks an image option from the analysis.
 */
async function renderCoverWithQuery(betSlipBase64, betSlipMime, analysis, imageQuery) {
  const requestBody = {
    headline: analysis.headline,
    betSlipBase64,
    betSlipMime,
    bgImageSearch: imageQuery,
    accentColor: analysis.accentColor || "#FF3B30",
    brandText: "ODDS",
    returnFormat: "base64",
  };

  try {
    const headers = { "Content-Type": "application/json" };
    if (DIGI_API_SECRET) headers["Authorization"] = `Bearer ${DIGI_API_SECRET}`;

    console.log(`[brain] Rendering cover with image query: "${imageQuery}"`);
    const res = await fetch(`${DIGI_API_URL}/api/stake/cover`, {
      method: "POST",
      headers,
      body: JSON.stringify(requestBody),
    });

    if (!res.ok) {
      const errText = await res.text();
      return { success: false, error: `Digi API error: ${res.status} — ${errText}` };
    }

    const data = await res.json();
    if (data.success && data.image) {
      return { success: true, imageBase64: data.image };
    }
    return { success: false, error: data.error || "Unknown Digi error" };
  } catch (e) {
    return { success: false, error: `Could not reach Digi: ${e.message}` };
  }
}

// -- Exports --------------------------------------------------------------

module.exports = {
  setBotInstance,
  startAutoCapture,
  captureMessage,
  getPipelineSummary,
  getDealAdvice,
  extractNightlyLessons,
  sendMorningRecap,
  sendNightlyRecap,
  analyzeBetSlip,
  generateBetSlipCover,
  renderCoverWithQuery,
  searchBetSlipImages,
  renderCoverWithImage,
};
